/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture, MeshTransmissionMaterial } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader, MeshToonMaterial } from "three";
import * as THREE from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF("/AirMaxOneFinal.glb");

  const textureSole = useTexture('./SoleColor.jpg')
  const textureSole1 = useTexture('./SoleColor1.jpg')
  textureSole.flipY = false
  textureSole.wrapS = THREE.RepeatWrapping
  textureSole.wrapT = THREE.RepeatWrapping
  textureSole.format = THREE.RGBAFormat
  textureSole1.flipY = false

  const textureTread = useTexture('./treadTexture.jpg')
  textureTread.flipY = false

  const textureSockTop = useTexture('./SockTopColor.jpg')
  textureSockTop.wrapS = THREE.RepeatWrapping
  // textureSockTop.flipY = false
   const textureSockNormal = useTexture('./SockTopNormal.jpg')

  const prop = useTexture({
    map:'SoleTrimColor.jpg',
    normalMap:'SoleTrimNormal.jpg' })
    prop.flipY = false

    const textureTissu = useTexture('./MaterialSock2.jpg')
    const textureTissuNormal = useTexture('./MaterialSockNormal.jpg')
    const textureNikeNormal = useTexture('./LogoNikeNormal.jpg')

    const texturelogolion = useTexture('./TaverneTransp.png')
    texturelogolion.wrapS = THREE.RepeatWrapping

  return (
    <group {...props} dispose={null}>

    {/* Bulle d'air */}
      <mesh
        
        geometry={nodes.BulleDair.geometry}
        material={materials["Material Bulle dair"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      {/* <meshPhysicalMaterial 
      color='#E7D540'
       roughness={0.107} 
       transmission={0.9} 
       clearcoatRoughness={1}
       envMapIntensity={0.6}
       thickness={0.5} /> */}
       
       <MeshTransmissionMaterial color='#E7D540'
       transmission={0.9} 
       roughness={0.107}
       thickness={0.5}
       backside={true} />
      </mesh>
      <mesh
        castShadow
        
        geometry={nodes.SoleTrim.geometry}
        material={materials["Material.Sole Trim"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
        <meshPhysicalMaterial color='#07230F' roughness={0.4} sheen={0.5}/>
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tread.geometry}
        material={materials["Material Tread"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      <meshPhysicalMaterial color='#CBBA1F' roughness={0.5}/>
      </mesh>
      <mesh
        geometry={nodes.Sole.geometry} 
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >

        <meshPhysicalMaterial map={textureSole} roughness={0.5}
         specularIntensity={0.5}
         />
      </mesh>


      <mesh
        geometry={nodes.treadtop.geometry}
        material={materials.Material}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      <meshPhysicalMaterial color='#CBBA1F' roughness={0.518} clearcoatRoughness={0.030} specularIntensity={0.5}/>
      </mesh>
      <mesh
        geometry={nodes.Sock002.geometry}
        material={materials["Material.004"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
       >
        <meshPhysicalMaterial normalMap={textureSockNormal} color='#07230F' roughness={0.5} sheen={0.5} normalScale={0.5}/>
       </mesh>
      <mesh
        geometry={nodes.Languette.geometry}
        material={materials["Material languette"]}
        position={[0, 0.18, 0]}
        scale={[0.53, 0.15, 0.14]}
      />
      <mesh
        geometry={nodes.Sock.geometry}
        material={materials["Material Sock"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      {/* <meshStandardMaterial map={textureTissu}  normalScale={0.5} roughness={0.75} sheen={0.9}/> */}
      </mesh>
      <mesh
        geometry={nodes.Sock003.geometry}
        material={materials["Material.005"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      <meshPhysicalMaterial color='#714F27' metalness={1}/>
      </mesh>
      <mesh
        geometry={nodes.Sock_back.geometry}
        material={materials["Material Sock Back"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      >
      <meshPhysicalMaterial color='#791525' roughness={0.4} sheen={0.5}/>
      </mesh>
      <mesh
        geometry={nodes.Etoile.geometry}
        material={materials["Material.007"]}
        position={[0, 0.05, 0.009]}
        scale={[1.15, 1, 1]}
      >
      <meshPhysicalMaterial color='#E7D453' roughness={0.5} />
      </mesh>
      <mesh
        geometry={nodes.CinqEtoiles.geometry}
        material={materials["Material.007"]}
        position={[0, 0.05, 0]}
      >
      <meshStandardMaterial color='#E7D453' roughness={0.5} />
      </mesh>
      <group
        position={[3.06, 1.05, -1.98]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
      >
        <mesh
         
          geometry={nodes.Plane003.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        geometry={nodes["lions-indomptables-cameroun-229674"].geometry}
        material={materials["lions-indomptables-cameroun-229674"]}
        position={[0, 2.01, 0]}
        rotation={[Math.PI / 2, 0, 0]}
       
      >
      <meshPhysicalMaterial map={texturelogolion} transparent={true} roughness={0.5}/>
      </mesh>
      <mesh
        geometry={nodes.Sock004.geometry}
        material={materials["Material Sock.002"]}
        position={[0, 1.07, -1.14]}
        scale={[0.53, 0.15, 0.15]}
      />
      <mesh
        castShadow
      
        geometry={nodes.Sock001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.12, 0]}
        scale={[0.53, 0.15, 0.15]}
      >
      <meshStandardMaterial color='#791525' roughness={0.5}></meshStandardMaterial>
      </mesh>
      <mesh
        geometry={nodes.Logo_Nike.geometry}
        material={materials["Material Logo Nike"]}
        position={[0, 0.12, 0]}
      >
      <meshPhysicalMaterial color='#C59133' displacementScale={0.1} normalScale={0.3}  metalness={1}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("/AirMaxOneFinal.glb");
